const trendingFoods=[
    {
      idMeal: "52786",
      strMeal: "Rocky Road Fudge",
      strDrinkAlternate: null,
      strCategory: "Dessert",
      strArea: "American",
      strInstructions: "Line an 8-inch-square baking pan with wax paper or foil, and coat with non-stick spray.\r\nPour ½ cup of the miniature marshmallows into the bottom of the lined baking dish.\r\nIn a microwave-safe bowl, combine the chocolate chips and peanut butter. Microwave the chocolate mixture in 20-second intervals, stirring in between each interval, until the chocolate is melted.\r\nAdd the vanilla extract and stir well, until smooth.\r\nReserve 2 tablespoons of the chopped almonds or peanuts, and set aside.\r\nFold 1 ½ cups of the miniature marshmallows and the remaining chopped nuts into the chocolate mixture.\r\nTransfer the chocolate mixture into the prepared pan and spread into an even layer. Immediately top with the reserved chopped nuts and the mallow bits or additional miniature marshmallows, if using.\r\nRefrigerate for 4 hours, or until set.\r\nRemove the fudge and wax paper from the pan. Carefully peel all of wax paper from the fudge.\r\nCut the fudge into bite-sized pieces and serve.",
      strMealThumb: "https://www.themealdb.com/images/media/meals/vtxyxv1483567157.jpg",
      strTags: "Chocolate,Snack,Sweet,Baking",
      strYoutube: "https://www.youtube.com/watch?v=N1aJ3nEYXyg",
      strIngredient1: "Miniature Marshmallows",
      strIngredient2: "Chocolate Chips",
      strIngredient3: "Peanut Butter",
      strIngredient4: "Vanilla Extract",
      strIngredient5: "Peanuts",
      strMeasure1: "2 cups",
      strMeasure2: "3 cups",
      strMeasure3: "½ cup",
      strMeasure4: "1 tsp",
      strMeasure5: "1 ¼ cups",
      strSource: "http://tiphero.com/rocky-road-fudge/",
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null
    },
    {
        idMeal: "52777",
        strMeal: "Mediterranean Pasta Salad",
        strDrinkAlternate: null,
        strCategory: "Seafood",
        strArea: "Italian",
        strInstructions: "Bring a large saucepan of salted water to the boil\r\nAdd the pasta, stir once and cook for about 10 minutes or as directed on the packet.\r\nMeanwhile, wash the tomatoes and cut into quarters. Slice the olives. Wash the basil.\r\nPut the tomatoes into a salad bowl and tear the basil leaves over them. Add a tablespoon of olive oil and mix.\r\nWhen the pasta is ready, drain into a colander and run cold water over it to cool it quickly.\r\nToss the pasta into the salad bowl with the tomatoes and basil.\r\nAdd the sliced olives, drained mozzarella balls, and chunks of tuna. Mix well and let the salad rest for at least half an hour to allow the flavours to mingle.\r\nSprinkle the pasta with a generous grind of black pepper and drizzle with the remaining olive oil just before serving.",
        strMealThumb: "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
        strTags: "Pasta,Baking",
        strYoutube: "https://www.youtube.com/watch?v=e52IL8zYmaE",
        strIngredient1: "mozzarella balls",
        strIngredient2: "baby plum tomatoes",
        strIngredient3: "fresh basil",
        strIngredient4: "farfalle",
        strIngredient5: "extra virgin olive oil",
        strIngredient6: "Green Olives",
        strIngredient7: "tuna",
        strIngredient8: "salt",
        strIngredient9: "pepper",
        strMeasure1: "200 g",
        strMeasure2: "250 g",
        strMeasure3: "1  bunch",
        strMeasure4: "350 g",
        strMeasure5: "3  tablespoons",
        strMeasure6: "40 g",
        strMeasure7: "200 g",
        strMeasure8: "to taste",
        strMeasure9: "to taste",
        strSource: "https://thelemonsqueezy.com/recipe/mediterranean-pasta-salad/",
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
      },
      {
        idMeal: "52819",
        strMeal: "Cajun spiced fish tacos",
        strDrinkAlternate: null,
        strCategory: "Seafood",
        strArea: "Mexican",
        strInstructions: "Cooking in a cajun spice and cayenne pepper marinade makes this fish super succulent and flavoursome. Top with a zesty dressing and serve in a tortilla for a quick, fuss-free main that's delightfully summery.\r\n\r\nOn a large plate, mix the cajun spice and cayenne pepper with a little seasoning and use to coat the fish all over.\r\n\r\nHeat a little oil in a frying pan, add in the fish and cook over a medium heat until golden. Reduce the heat and continue frying until the fish is cooked through, about 10 minutes. Cook in batches if you don’t have enough room in the pan.\r\n\r\nMeanwhile, prepare the dressing by combining all the ingredients with a little seasoning.\r\nSoften the tortillas by heating in the microwave for 5-10 seconds. Pile high with the avocado, lettuce and spring onion, add a spoonful of salsa, top with large flakes of fish and drizzle over the dressing.",
        strMealThumb: "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
        strTags: "Spicy,Fish",
        strYoutube: "https://www.youtube.com/watch?v=N4EdUt0Ou48",
        strIngredient1: "cajun",
        strIngredient2: "cayenne pepper",
        strIngredient3: "white fish",
        strIngredient4: "vegetable oil",
        strIngredient5: "flour tortilla",
        strIngredient6: "avocado",
        strIngredient7: "little gem lettuce",
        strIngredient8: "spring onion",
        strIngredient9: "salsa",
        strIngredient10: "sour cream",
        strIngredient11: "lemon",
        strIngredient12: "garlic",
        strMeasure1: "2 tbsp",
        strMeasure2: "1 tsp",
        strMeasure3: "4 fillets",
        strMeasure4: "1 tsp",
        strMeasure5: "8",
        strMeasure6: "1 sliced",
        strMeasure7: "2 shredded",
        strMeasure8: "4 shredded",
        strMeasure9: "1 x 300ml",
        strMeasure10: "1 pot",
        strMeasure11: "1",
        strMeasure12: "1 clove finely chopped",
        strSource: "https://realfood.tesco.com/recipes/cajun-spiced-fish-tacos.html",
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null
        },
        {
            idMeal: "52771",
            strMeal: "Spicy Arrabiata Penne",
            strDrinkAlternate: null,
            strCategory: "Vegetarian",
            strArea: "Italian",
            strInstructions: "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
            strMealThumb: "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
            strTags: "Pasta,Curry",
            strYoutube: "https://www.youtube.com/watch?v=1IszT_guI08",
            strIngredient1: "penne rigate",
            strIngredient2: "olive oil",
            strIngredient3: "garlic",
            strIngredient4: "chopped tomatoes",
            strIngredient5: "red chile flakes",
            strIngredient6: "italian seasoning",
            strIngredient7: "basil",
            strIngredient8: "Parmigiano-Reggiano",
            strIngredient9: "",
            strIngredient10: "",
            strIngredient11: "",
            strIngredient12: "",
            strIngredient13: "",
            strIngredient14: "",
            strIngredient15: "",
            strIngredient16: null,
            strIngredient17: null,
            strIngredient18: null,
            strIngredient19: null,
            strIngredient20: null,
            strMeasure1: "1 pound",
            strMeasure2: "1/4 cup",
            strMeasure3: "3 cloves",
            strMeasure4: "1 tin ",
            strMeasure5: "1/2 teaspoon",
            strMeasure6: "1/2 teaspoon",
            strMeasure7: "6 leaves",
            strMeasure8: "spinkling",
            strMeasure9: "",
            strMeasure10: "",
            strMeasure11: "",
            strMeasure12: "",
            strMeasure13: "",
            strMeasure14: "",
            strMeasure15: "",
            strMeasure16: null,
            strMeasure17: null,
            strMeasure18: null,
            strMeasure19: null,
            strMeasure20: null,
            strSource: null,
            strImageSource: null,
            strCreativeCommonsConfirmed: null,
            dateModified: null
          }
]

export default trendingFoods